#!/bin/bash
echo "🔍 API Key Kontrol Rehberi"
echo ""
echo "1️⃣  Testnet API Key Alın:"
echo "   https://testnet.binancefuture.com/"
echo "   GitHub ile giriş yapın"
echo "   API Key oluşturun"
echo ""
echo "2️⃣  .env Dosyasını Kontrol Edin:"
echo "   - Tırnak işareti OLMAMALI"
echo "   - Boşluk OLMAMALI"
echo "   - Örnek:"
echo "     BINANCE_API_KEY=abc123xyz"
echo "     BINANCE_API_SECRET=def456uvw"
echo ""
echo "3️⃣  Testnet Modu Açık Olmalı:"
echo "   BINANCE_TESTNET=true"
echo ""
echo "4️⃣  Dosyayı Kontrol Edin:"
echo "   grep 'BINANCE_API' .env"
echo ""
