#!/bin/bash
echo "🔧 .env Dosyası Düzeltme Yardımcısı"
echo ""
echo "Lütfen .env dosyasında şunu değiştirin:"
echo ""
echo "❌ DB_USER=postgres"
echo "✅ DB_USER=huseynli99"
echo ""
echo "Ayrıca API Key'lerin doğru olduğundan emin olun:"
echo "- Testnet API: https://testnet.binancefuture.com/"
echo "- Tırnak işareti KULLANMAYIN"
echo ""
echo "Dosyayı açmak için:"
echo "   open -e .env"
echo ""
