symbols:
  core:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - SOLUSDT
    - XRPUSDT
    - ADAUSDT
    - DOGEUSDT
    - LINKUSDT
    - LTCUSDT
    - DOTUSDT
  extended:
    - AVAXUSDT
    - MATICUSDT
    - TRXUSDT
    - ATOMUSDT
    - BCHUSDT
    - OPUSDT
    - ARBUSDT
    - APTUSDT
    - LDOUSDT
    - SUIUSDT
settings:
  interval: 1h
  lookback_limit: 720
  base_url: https://data-api.binance.vision/api/v3/klines
  rate_limit_per_minute: 1100
