experiment:
  name: "btc_dqn_1h"
  output_dir: "runs"
  seed: 42

log:
  print_freq: 1000
  eval_interval: 5000
  checkpoint_interval: 10000
  top_k_checkpoints: 3

data:
  csv_path: "data/btcusdt_1h_ext.csv"
  time_col: "timestamp"
  price_col: "close"
  feature_cols: ["close"]
  window: 128
  splits:
    train: 0.7
    val: 0.15
    test: 0.15
  purge_bars: 24
  fill_method: "ffill"

environment:
  cost_bps: 2.0
  action_levels: [-1.0, -0.5, 0.0, 0.5, 1.0]
  reward_scale: 1.0
  cooldown_bars: 3
  max_drawdown: 0.25
  trend_filter_abs_return: 0.0005
  volatility_ceiling: 0.05

model:
  type: "mlp_dueling"
  hidden_sizes: [256, 256]
  dueling: true
  distributional:
    enabled: false
    num_atoms: 51
    v_min: -0.05
    v_max: 0.05
  dropout: 0.1
  use_gru: true
  gru_hidden_size: 128

training:
  device: "auto"
  max_steps: 250000
  warmup_steps: 20000
  batch_size: 256
  gamma: 0.995
  lr: 0.00025
  weight_decay: 1.0e-5
  gradient_clip: 1.0
  target_update_interval: 4000
  eval_episodes: 1
  early_stopping:
    metric: "val_sharpe"
    patience: 10
  use_per: true
  per_alpha: 0.6
  per_beta_start: 0.4
  per_beta_frames: 150000
  lr_scheduler:
    type: cosine
    t_max: 250000
    eta_min: 0.00005
  epsilon:
    start: 1.0
    end: 0.02
    decay_steps: 80000
    cycle_length: 160000
    warmup_steps: 5000

inference:
  hysteresis_threshold: 0.002
  cooldown_bars: 3
