experiment:
  name: "btc_dqn_eval"
  output_dir: "runs"
  seed: 42

data:
  csv_path: "data/btcusdt_1h.csv"
  time_col: "timestamp"
  price_col: "close"
  feature_cols: ["close"]
  window: 43
  splits:
    train: 0.6
    val: 0.2
    test: 0.2
  purge_bars: 0
  fill_method: "ffill"

environment:
  cost_bps: 2.0
  action_levels: [-1.0, -0.5, 0.0, 0.5, 1.0]
  reward_scale: 1.0
  cooldown_bars: 2
  max_drawdown: 0.25

model:
  type: "mlp_dueling"
  hidden_sizes: [256, 256]
  dueling: true
  distributional:
    enabled: false
  dropout: 0.1
  use_gru: true
  gru_hidden_size: 128

training:
  device: "cpu"
  max_steps: 10000
  warmup_steps: 1000
  batch_size: 128
  gamma: 0.995
  lr: 0.0003
  weight_decay: 1.0e-5
  gradient_clip: 1.0
  epsilon:
    start: 1.0
    end: 0.02
    decay_steps: 5000
  target_update_interval: 1000
  eval_episodes: 1
  early_stopping:
    metric: "val_sharpe"
    patience: 5
  use_per: true
  per_alpha: 0.6
  per_beta_start: 0.5
  per_beta_frames: 40000

log:
  print_freq: 500
  eval_interval: 2000
  checkpoint_interval: 5000
  top_k_checkpoints: 1

inference:
  hysteresis_threshold: 0.002
  cooldown_bars: 3
